server:
  port: 8080
spring:
  application:
    name: PhoneBookAppApplication
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    url: jdbc:h2:~/test
    username: sa
    #property to enable console to H2 database
    #Url is http://localhost:8080/h2-console
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
